version: '3.8'
services:
  web:
    build: ./flask  # Correct build context
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./flask:/app  # Only mount flask dir
    # ports:  # Remove host port mapping (handled by nginx)
    depends_on:
      - db
    environment: 
      # Keep existing DB env vars

  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      # Keep existing MySQL env vars

  nginx:  # Renamed from "proxy"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web  # Correct service name

volumes:
  mysql-data:
