version: '3.8'
services:
  backend:
    build: ./flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DB=appdb
    depends_on:
      - db

  db:
    image: mysql:8.0.19
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=appdb
    ports:
      - "3306:3306"

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend


